[project]
name = "yologram-api-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "pydantic-settings>=2.14.0",
    "uvicorn>=0.46.0",
    "opentelemetry-sdk>=1.20.0",
    "opentelemetry-exporter-otlp-proto-http>=1.20.0",
    "opentelemetry-instrumentation-system-metrics>=0.42b0",
    "opentelemetry-instrumentation-fastapi>=0.42b0",
]
