name: v2-frontend

on:
  push:
    branches: [master]
    paths:
      - 'v2/yologram-web-v2/**'
  pull_request:
    branches: [master]
    paths:
      - 'v2/yologram-web-v2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
