server:
  port: 5002

spring:
  config:
    import:
      - 'aws-parameterstore:/yologram/service/yologram-api-v1_local/'
      - 'aws-parameterstore:/yologram/service/yologram-api-v1_prod/'
  cloud:
    aws:
      credentials:
        profile:
          name: yologram
