spring:
  config:
    import:
      - 'aws-parameterstore:/yologram/service/yologram-api-v1_prod/'

cache:
  data:
    redis:
      host:

database:
  main:
    writer:
      datasource:
        url:
        username:
        password:
    reader:
      datasource:
        url:
        username:
        password:
    jpa:
      properties:
        hibernate.hbm2ddl.auto: validate
      show-sql: false